#!/usr/bin/env python3
"""Smoke-check PHM imports from a sourced colcon install overlay.

Run after `colcon build` and `source install/setup.bash`. With
`--symlink-install`, imported modules may legitimately resolve through `src/`;
the invariant is that imports work from outside the repository through the
colcon overlay, without manual source-tree `PYTHONPATH` setup.
"""

from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path

from ament_index_python.packages import get_package_share_directory

MODULES = [
    # phm_msgs is generated by rosidl into the install space only; it has no
    # source-tree fallback, so importing it proves the overlay is really live.
    "phm_msgs.msg",
    "phm_core",
    "phm_detectors",
    "phm_ood",
    "phm_arbiter",
    "phm_recovery",
    "phm_sim",
    "phm_ood.node",
    "phm_arbiter.arbiter_node",
    "phm_detectors.phm_detectors_node",
    "phm_recovery.recovery_node",
    "phm_sim.embedding_publisher_node",
]

# ament_python packages whose importable code also exists in the source tree.
PYTHON_PACKAGES = [
    "phm_core",
    "phm_detectors",
    "phm_ood",
    "phm_arbiter",
    "phm_recovery",
    "phm_sim",
]

# Every colcon package that must be resolvable through the ament index,
# including the two non-Python ones (generated messages and the C++ detector).
PACKAGES = ["phm_msgs", "phm_ood_cpp", *PYTHON_PACKAGES]


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _phm_source_roots(repo_root: Path) -> set[Path]:
    return {repo_root / "src" / package / package for package in PYTHON_PACKAGES}


def _module_file(module_name: str) -> Path:
    module = importlib.import_module(module_name)
    module_file = getattr(module, "__file__", None)
    if not module_file:
        raise AssertionError(f"{module_name} has no __file__; cannot verify import origin")
    return Path(module_file).resolve()


def main() -> int:
    repo_root = _repo_root()
    phm_source_roots = {path.resolve() for path in _phm_source_roots(repo_root)}
    src_root = (repo_root / "src").resolve()
    install_prefix = os.environ.get("COLCON_CURRENT_PREFIX") or os.environ.get("AMENT_PREFIX_PATH")
    if not install_prefix:
        print(
            "ERROR: no colcon overlay detected. Run: "
            "source /opt/ros/humble/setup.bash && source install/setup.bash",
            file=sys.stderr,
        )
        return 2

    failures: list[str] = []
    manual_pythonpath = [
        Path(entry).resolve()
        for entry in os.environ.get("PYTHONPATH", "").split(os.pathsep)
        if entry
    ]
    for entry in manual_pythonpath:
        if entry == src_root or entry in phm_source_roots:
            failures.append(f"manual PYTHONPATH points at PHM source tree: {entry}")

    for entry in map(Path, sys.path):
        if not str(entry):
            continue
        resolved = entry.resolve()
        if resolved == src_root or resolved in phm_source_roots:
            failures.append(f"sys.path points at PHM source tree before import: {resolved}")

    for package_name in PACKAGES:
        try:
            share_dir = Path(get_package_share_directory(package_name)).resolve()
        except Exception as exc:  # noqa: BLE001 - smoke script should report every package failure.
            failures.append(f"{package_name}: not found in ament index: {exc}")
            continue
        print(f"ament OK: {package_name} -> {share_dir}")

    for module_name in MODULES:
        try:
            module_path = _module_file(module_name)
        except Exception as exc:  # noqa: BLE001 - smoke script should report every import failure.
            failures.append(f"{module_name}: import failed: {exc}")
            continue
        print(f"import OK: {module_name} -> {module_path}")

    if failures:
        print("Install import smoke FAILED:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1

    print("Install import smoke PASSED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
